webtalk_init -webtalk_dir C:/Users/C22Christopher.Katz/Documents/20_spring_school/ECE 281/ece281_katz_christopher/Lab_1/Lab_1/Lab_1.sim/sim_1/behav/xsim/xsim.dir/thirtyOneDayMonth_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Feb 10 21:26:48 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4cfc0c6c-c04d-4ba9-9a48-95d142bc866e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "eb53c1cbd9d44f92a70a01d28acb6074" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2112 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "200 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7264_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2255648003 -regid "" -xml C:/Users/C22Christopher.Katz/Documents/20_spring_school/ECE 281/ece281_katz_christopher/Lab_1/Lab_1/Lab_1.sim/sim_1/behav/xsim/xsim.dir/thirtyOneDayMonth_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/C22Christopher.Katz/Documents/20_spring_school/ECE 281/ece281_katz_christopher/Lab_1/Lab_1/Lab_1.sim/sim_1/behav/xsim/xsim.dir/thirtyOneDayMonth_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/C22Christopher.Katz/Documents/20_spring_school/ECE 281/ece281_katz_christopher/Lab_1/Lab_1/Lab_1.sim/sim_1/behav/xsim/xsim.dir/thirtyOneDayMonth_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
